---
driver:
  # you can restore this if you want, but it'll be slooooooow
  #name: vagrant
  name: docker
  use_sudo: false

provisioner:
  # it would be nice if this supported multiple provisioners (ordered) like vagrant does...
  #name: shell
  name: chef_solo
  require_chef_omnibus: 12.21.4

platforms:
  - name: ubuntu-16.04
  # debian: stable, oldstable
  # TODO 7.9 and 8.2 were recently released
  - name: debian-7.8
  - name: debian-8.1
  # centos
  - name: centos-5.11
  # TODO 6.7 is the latest
  - name: centos-6.6
  - name: centos-7.1.1503
  # redhat: 5.9, 6.6, 7.1
  # TODO what's the platform name in docker?

suites:
  - name: default
    run_list:
      - recipe[anaconda::default]
    attributes:
      anaconda:
        version: '5.0.1'
        python_version: 'python3'
        flavor: 'x86_64'
        accept_license: 'yes'
